/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FLabelWrapper: typeof import('./src/components/FLabelWrapper.vue')['default']
    FRadio: typeof import('./src/components/FRadio.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
